version: "3.9"
services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - SERVICE_B_URL=http://service-b:8080
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - service-b
      - zipkin

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - WEATHER_API_TOKEN=API_VALIDA
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
