version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RATE_LIMITER_IP_LIMIT=10
      - RATE_LIMITER_TOKEN_LIMIT=100
      - RATE_LIMITER_BLOCK_TIME=300
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    depends_on:
      - redis
